
export const getMockArticles = (language: string) => {
  return language === 'en' ? mockArticlesEn : mockArticlesEs;
};

const mockArticlesEn = [
  {
    id: '1',
    title_es: 'Artistas de Puerto Vallarta Transforman el Espacio Público',
    title_en: 'Puerto Vallarta Artists Transforming Public Space',
    title: 'Puerto Vallarta Artists Transforming Public Space',
    dek_es: 'Un colectivo de muralistas y escultores convierte las calles de PV en galería abierta.',
    dek_en: 'A collective of muralists and sculptors turns PV\'s streets into an open-air gallery.',
    content: 'A growing collective of visual artists, muralists, and sculptors from Puerto Vallarta are making their mark on the national and international art scene. From the Zona Romántica to the Malecón, their work transforms public spaces into open-air museums celebrating Pacific coast culture.',
    image_url: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / PV Arts Collective',
    category: 'arte',
    location: 'Puerto Vallarta',
    created_at: '2026-06-01T00:00:00.000Z',
    updated_at: '2026-06-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'June 1, 2026',
    language: 'en',
    featured: true,
    positive_angle: 'Artistas locales revitalizan espacios urbanos con arte accesible y comunitario.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '2',
    title_es: 'El Nuevo Sonido de México: Músicos Independientes que Redefinen LATAM',
    title_en: 'The New Sound of Mexico: Independent Musicians Redefining LATAM',
    title: 'The New Sound of Mexico: Independent Musicians Redefining LATAM',
    dek_es: 'De los estudios de Guadalajara a las azoteas de Oaxaca, una generación reescribe la música mexicana.',
    dek_en: 'From Guadalajara studios to Oaxaca rooftops, a generation rewrites Mexican music.',
    content: 'From garage studios in Guadalajara to rooftop sessions in Oaxaca, a new generation of independent musicians is blending regional rhythms with global influences. Streaming numbers confirm what audiences already feel — Mexican music is having a global moment.',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Music Mexico',
    category: 'musica',
    location: 'Guadalajara',
    created_at: '2026-05-20T00:00:00.000Z',
    updated_at: '2026-05-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 20, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'La música independiente mexicana conquista mercados globales.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '3',
    title_es: 'Mariposas Monarca: Victoria de Conservación en Michoacán',
    title_en: 'Monarch Butterflies: Conservation Victory in Michoacán',
    title: 'Monarch Butterflies: Conservation Victory in Michoacán',
    dek_es: 'Por primera vez en una década, la población de mariposa monarca se recupera significativamente.',
    dek_en: 'For the first time in a decade, the monarch butterfly population rebounds significantly.',
    content: 'For the first time in a decade, butterfly experts are reporting a significant rebound in the monarch population at the Reserva de la Biosfera Mariposa Monarca. Local communities credit sustainable tourism and reforestation programs for the turnaround.',
    image_url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Naturaleza México',
    category: 'naturaleza',
    location: 'Michoacán',
    created_at: '2026-04-10T00:00:00.000Z',
    updated_at: '2026-04-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 10, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'La comunidad y el ecoturismo revierten el declive de la mariposa monarca.',
    affiliate_opportunity: { type: 'ecoturismo', partner: 'Reserva Biosfera' },
    status: 'published',
  },
  {
    id: '4',
    title_es: 'Huertos Urbanos Comunitarios Florecen en la CDMX',
    title_en: 'Community Urban Gardens Bloom Across Mexico City',
    title: 'Community Urban Gardens Bloom Across Mexico City',
    dek_es: 'El Huerto Monarca de La Labyrinha es modelo replicado en toda la capital.',
    dek_en: 'El Huerto Monarca in La Labyrinha becomes a model replicated across the capital.',
    content: 'In colonias that once lacked green space, community-driven urban gardens are sprouting up, bringing neighbors together and improving food security. La Labyrinha\'s own garden project, El Huerto Monarca, serves as a model being replicated across the capital.',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Urban Gardens',
    category: 'vida_sustentable',
    location: 'CDMX',
    created_at: '2026-05-15T00:00:00.000Z',
    updated_at: '2026-05-15T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 15, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'Jardines comunitarios transforman colonias y mejoran la soberanía alimentaria.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '5',
    title_es: 'Surf, Arte y Alma: La Cultura Creativa de Puerto Vallarta',
    title_en: 'Surf, Art, and Soul: Puerto Vallarta\'s Creative Culture',
    title: 'Surf, Art, and Soul: Puerto Vallarta\'s Creative Culture',
    dek_es: 'PV es donde los surfistas, pintores, poetas y chefs se cruzan a diario.',
    dek_en: 'PV is where surfers, painters, poets, and chefs collide daily.',
    content: 'Puerto Vallarta is much more than its famous beaches — it\'s a city where surfers, painters, poets, and chefs collide daily. As September approaches, the creative community is gearing up for a celebration that could put PV on the cultural map permanently.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / PV Beaches',
    category: 'viajes',
    location: 'Puerto Vallarta',
    created_at: '2026-05-10T00:00:00.000Z',
    updated_at: '2026-05-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 10, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'Puerto Vallarta se posiciona como destino cultural creativo y sustentable.',
    affiliate_opportunity: { type: 'hotel', partner: 'PV Tourism Board' },
    status: 'published',
  },
  {
    id: '6',
    title_es: 'IA Mexicana: Startups que Resuelven Problemas Locales con Tecnología Global',
    title_en: 'Mexican AI: Startups Solving Local Problems with Global Tech',
    title: 'Mexican AI: Startups Solving Local Problems with Global Tech',
    dek_es: 'Emprendedores mexicanos aplican IA a desafíos únicos de Latinoamérica.',
    dek_en: 'Mexican entrepreneurs apply AI to challenges unique to Latin America.',
    content: 'A new wave of Mexican entrepreneurs is applying AI, blockchain, and clean tech to challenges unique to Latin America — from informal housing to water distribution. Investors from Silicon Valley to Madrid are taking notice.',
    image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Tech Mexico',
    category: 'ia',
    location: 'CDMX',
    created_at: '2026-05-05T00:00:00.000Z',
    updated_at: '2026-05-05T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 5, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'La tecnología mexicana aborda retos sociales con soluciones innovadoras.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '7',
    title_es: 'Diseño Oaxaqueño: Cómo las Tejedoras de Teotitlán Conquistan el Mundo',
    title_en: 'Oaxacan Design: How Teotitlán Weavers Are Conquering the World',
    title: 'Oaxacan Design: How Teotitlán Weavers Are Conquering the World',
    dek_es: 'Una cooperativa de mujeres zapotecas convierte el tejido ancestral en exportación global.',
    dek_en: 'A cooperative of Zapotec women turns ancestral weaving into global exports.',
    content: 'In Teotitlán del Valle, a cooperative of women weavers has turned ancestral textile knowledge into a thriving export business. Their story is one of tradition, innovation, and fierce pride in Zapotec identity.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Oaxaca Textiles',
    category: 'diseño',
    location: 'Oaxaca',
    created_at: '2026-04-01T00:00:00.000Z',
    updated_at: '2026-04-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 1, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'El diseño textil indígena mexicano encuentra mercados internacionales sin perder su esencia.',
    affiliate_opportunity: { type: 'artesanía', partner: 'Cooperativa Teotitlán' },
    status: 'published',
  },
  {
    id: '8',
    title_es: 'Fotografía: La Belleza Oculta de los Mercados de México',
    title_en: 'Photography: The Hidden Beauty of Mexico\'s Markets',
    title: 'Photography: The Hidden Beauty of Mexico\'s Markets',
    dek_es: 'Seis fotógrafos exploran el color, el caos y la comunidad de los mercados mexicanos.',
    dek_en: 'Six photographers explore the colour, chaos, and community of Mexican markets.',
    content: 'Through the lens of six photographers from different parts of the country, this photo essay explores the color, chaos, and community of Mexico\'s mercados — from the massive Central de Abastos to the smallest village tianguis.',
    image_url: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Mexico Markets',
    category: 'arte',
    location: 'México',
    created_at: '2026-03-22T00:00:00.000Z',
    updated_at: '2026-03-22T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'March 22, 2026',
    language: 'en',
    featured: false,
    positive_angle: 'Los mercados tradicionales son el corazón cultural y social de México.',
    affiliate_opportunity: null,
    status: 'published',
  },
];

const mockArticlesEs = [
  {
    id: '1-es',
    title_es: 'Artistas de Puerto Vallarta Transforman el Espacio Público',
    title_en: 'Puerto Vallarta Artists Transforming Public Space',
    title: 'Artistas de Puerto Vallarta Transforman el Espacio Público',
    dek_es: 'Un colectivo de muralistas y escultores convierte las calles de PV en galería abierta.',
    dek_en: 'A collective of muralists and sculptors turns PV\'s streets into an open-air gallery.',
    content: 'Un colectivo creciente de artistas visuales, muralistas y escultores de Puerto Vallarta están dejando su huella en la escena artística nacional e internacional. Desde la Zona Romántica hasta el Malecón, su trabajo transforma los espacios públicos en museos al aire libre que celebran la cultura de la costa del Pacífico.',
    image_url: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / PV Arts Collective',
    category: 'arte',
    location: 'Puerto Vallarta',
    created_at: '2026-06-01T00:00:00.000Z',
    updated_at: '2026-06-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '1 de junio, 2026',
    language: 'es',
    featured: true,
    positive_angle: 'Artistas locales revitalizan espacios urbanos con arte accesible y comunitario.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '2-es',
    title_es: 'El Nuevo Sonido de México: Músicos Independientes que Redefinen LATAM',
    title_en: 'The New Sound of Mexico: Independent Musicians Redefining LATAM',
    title: 'El Nuevo Sonido de México: Músicos Independientes que Redefinen LATAM',
    dek_es: 'De los estudios de Guadalajara a las azoteas de Oaxaca, una generación reescribe la música mexicana.',
    dek_en: 'From Guadalajara studios to Oaxaca rooftops, a generation rewrites Mexican music.',
    content: 'Desde estudios de garaje en Guadalajara hasta sesiones en azoteas de Oaxaca, una nueva generación de músicos independientes mezcla ritmos regionales con influencias globales. Las cifras de streaming confirman lo que el público ya siente: la música mexicana está viviendo un momento global.',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Music Mexico',
    category: 'musica',
    location: 'Guadalajara',
    created_at: '2026-05-20T00:00:00.000Z',
    updated_at: '2026-05-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '20 de mayo, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'La música independiente mexicana conquista mercados globales.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '3-es',
    title_es: 'Mariposas Monarca: Victoria de Conservación en Michoacán',
    title_en: 'Monarch Butterflies: Conservation Victory in Michoacán',
    title: 'Mariposas Monarca: Victoria de Conservación en Michoacán',
    dek_es: 'Por primera vez en una década, la población de mariposa monarca se recupera significativamente.',
    dek_en: 'For the first time in a decade, the monarch butterfly population rebounds significantly.',
    content: 'Por primera vez en una década, los expertos en mariposas reportan un repunte significativo en la población monarca en la Reserva de la Biosfera Mariposa Monarca. Las comunidades locales atribuyen el giro al turismo sostenible y los programas de reforestación.',
    image_url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Naturaleza México',
    category: 'naturaleza',
    location: 'Michoacán',
    created_at: '2026-04-10T00:00:00.000Z',
    updated_at: '2026-04-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '10 de abril, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'La comunidad y el ecoturismo revierten el declive de la mariposa monarca.',
    affiliate_opportunity: { type: 'ecoturismo', partner: 'Reserva Biosfera' },
    status: 'published',
  },
  {
    id: '4-es',
    title_es: 'Huertos Urbanos Comunitarios Florecen en la CDMX',
    title_en: 'Community Urban Gardens Bloom Across Mexico City',
    title: 'Huertos Urbanos Comunitarios Florecen en la CDMX',
    dek_es: 'El Huerto Monarca de La Labyrinha es modelo replicado en toda la capital.',
    dek_en: 'El Huerto Monarca in La Labyrinha becomes a model replicated across the capital.',
    content: 'En colonias que antes carecían de espacios verdes, los huertos urbanos comunitarios están brotando, uniendo a vecinos y mejorando la seguridad alimentaria. El propio proyecto de huerto de La Labyrinha, el Huerto Monarca, sirve como modelo que se replica en toda la capital.',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Urban Gardens',
    category: 'vida_sustentable',
    location: 'CDMX',
    created_at: '2026-05-15T00:00:00.000Z',
    updated_at: '2026-05-15T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '15 de mayo, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'Jardines comunitarios transforman colonias y mejoran la soberanía alimentaria.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '5-es',
    title_es: 'Surf, Arte y Alma: La Cultura Creativa de Puerto Vallarta',
    title_en: 'Surf, Art, and Soul: Puerto Vallarta\'s Creative Culture',
    title: 'Surf, Arte y Alma: La Cultura Creativa de Puerto Vallarta',
    dek_es: 'PV es donde los surfistas, pintores, poetas y chefs se cruzan a diario.',
    dek_en: 'PV is where surfers, painters, poets, and chefs collide daily.',
    content: 'Puerto Vallarta es mucho más que sus famosas playas: es una ciudad donde surfistas, pintores, poetas y chefs se cruzan a diario. A medida que se acerca septiembre, la comunidad creativa se prepara para una celebración que podría poner a PV permanentemente en el mapa cultural.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / PV Beaches',
    category: 'viajes',
    location: 'Puerto Vallarta',
    created_at: '2026-05-10T00:00:00.000Z',
    updated_at: '2026-05-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '10 de mayo, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'Puerto Vallarta se posiciona como destino cultural creativo y sustentable.',
    affiliate_opportunity: { type: 'hotel', partner: 'PV Tourism Board' },
    status: 'published',
  },
  {
    id: '6-es',
    title_es: 'IA Mexicana: Startups que Resuelven Problemas Locales con Tecnología Global',
    title_en: 'Mexican AI: Startups Solving Local Problems with Global Tech',
    title: 'IA Mexicana: Startups que Resuelven Problemas Locales con Tecnología Global',
    dek_es: 'Emprendedores mexicanos aplican IA a desafíos únicos de Latinoamérica.',
    dek_en: 'Mexican entrepreneurs apply AI to challenges unique to Latin America.',
    content: 'Una nueva ola de emprendedores mexicanos aplica IA, blockchain y tecnología limpia a desafíos únicos de América Latina, desde vivienda informal hasta distribución de agua. Inversionistas de Silicon Valley a Madrid están tomando nota.',
    image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Tech Mexico',
    category: 'ia',
    location: 'CDMX',
    created_at: '2026-05-05T00:00:00.000Z',
    updated_at: '2026-05-05T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '5 de mayo, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'La tecnología mexicana aborda retos sociales con soluciones innovadoras.',
    affiliate_opportunity: null,
    status: 'published',
  },
  {
    id: '7-es',
    title_es: 'Diseño Oaxaqueño: Cómo las Tejedoras de Teotitlán Conquistan el Mundo',
    title_en: 'Oaxacan Design: How Teotitlán Weavers Are Conquering the World',
    title: 'Diseño Oaxaqueño: Cómo las Tejedoras de Teotitlán Conquistan el Mundo',
    dek_es: 'Una cooperativa de mujeres zapotecas convierte el tejido ancestral en exportación global.',
    dek_en: 'A cooperative of Zapotec women turns ancestral weaving into global exports.',
    content: 'En Teotitlán del Valle, una cooperativa de tejedoras ha convertido el conocimiento textil ancestral en un negocio de exportación floreciente. Su historia es de tradición, innovación y feroz orgullo en la identidad zapoteca.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Oaxaca Textiles',
    category: 'diseño',
    location: 'Oaxaca',
    created_at: '2026-04-01T00:00:00.000Z',
    updated_at: '2026-04-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '1 de abril, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'El diseño textil indígena mexicano encuentra mercados internacionales sin perder su esencia.',
    affiliate_opportunity: { type: 'artesanía', partner: 'Cooperativa Teotitlán' },
    status: 'published',
  },
  {
    id: '8-es',
    title_es: 'Fotografía: La Belleza Oculta de los Mercados de México',
    title_en: 'Photography: The Hidden Beauty of Mexico\'s Markets',
    title: 'Fotografía: La Belleza Oculta de los Mercados de México',
    dek_es: 'Seis fotógrafos exploran el color, el caos y la comunidad de los mercados mexicanos.',
    dek_en: 'Six photographers explore the colour, chaos, and community of Mexican markets.',
    content: 'A través del lente de seis fotógrafos de diferentes partes del país, este ensayo fotográfico explora el color, el caos y la comunidad de los mercados de México, desde la gigantesca Central de Abastos hasta el tianguis más pequeño de aldea.',
    image_url: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    image_credit: 'Unsplash / Mexico Markets',
    category: 'arte',
    location: 'México',
    created_at: '2026-03-22T00:00:00.000Z',
    updated_at: '2026-03-22T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '22 de marzo, 2026',
    language: 'es',
    featured: false,
    positive_angle: 'Los mercados tradicionales son el corazón cultural y social de México.',
    affiliate_opportunity: null,
    status: 'published',
  },
];
