
export const getMockArticles = (language: string) => {
  return language === 'en' ? mockArticlesEn : mockArticlesEs;
};

const mockArticlesEn = [
  {
    id: '1',
    title: 'Puerto Vallarta Artists Creating Waves Across Mexico',
    content: 'A growing collective of visual artists, muralists, and sculptors from Puerto Vallarta are making their mark on the national and international art scene. From the Zona Romántica to the Malecón, their work transforms public spaces into open-air museums celebrating Pacific coast culture.',
    image_url: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Art & Culture',
    created_at: '2026-06-01T00:00:00.000Z',
    updated_at: '2026-06-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'June 1, 2026',
    language: 'en',
    featured: true,
  },
  {
    id: '2',
    title: 'Youth Entrepreneurs Transform Barrio Santa María',
    content: 'Young entrepreneurs from the historic Barrio Santa María in La Labyrinha, Mexico City, are launching social businesses that create jobs and preserve their neighborhood\'s cultural identity. Meet the teens and twenty-somethings building the future right where they grew up.',
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Youth',
    created_at: '2026-05-28T00:00:00.000Z',
    updated_at: '2026-05-28T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 28, 2026',
    language: 'en',
  },
  {
    id: '3',
    title: 'Interview: Muralist Valentina Reyes on Painting Puerto Vallarta\'s Soul',
    content: 'Valentina Reyes grew up in Colonia Emiliano Zapata and today her murals can be seen from San Sebastián del Oeste to the Olas Altas boardwalk. We sat down with her to talk about inspiration, identity, and what it means to carry culture on your brush.',
    image_url: 'https://images.unsplash.com/photo-1460574283810-2aab119d8511?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Interviews',
    created_at: '2026-05-25T00:00:00.000Z',
    updated_at: '2026-05-25T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 25, 2026',
    language: 'en',
  },
  {
    id: '4',
    title: 'The New Sound of Mexico: Independent Musicians Redefining LATAM',
    content: 'From garage studios in Guadalajara to rooftop sessions in Oaxaca, a new generation of independent musicians is blending regional rhythms with global influences. Streaming numbers confirm what audiences already feel — Mexican music is having a global moment.',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Music',
    created_at: '2026-05-20T00:00:00.000Z',
    updated_at: '2026-05-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 20, 2026',
    language: 'en',
  },
  {
    id: '5',
    title: 'Community Gardens Bloom Across Mexico City\'s Forgotten Neighborhoods',
    content: 'In colonias that once lacked green space, community-driven urban gardens are sprouting up, bringing neighbors together and improving food security. La Labyrinha\'s own garden project, El Huerto Monarca, serves as a model being replicated across the capital.',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Community',
    created_at: '2026-05-15T00:00:00.000Z',
    updated_at: '2026-05-15T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 15, 2026',
    language: 'en',
  },
  {
    id: '6',
    title: 'Surf, Art, and Soul: Puerto Vallarta\'s Creative Beach Culture',
    content: 'Puerto Vallarta is much more than its famous beaches — it\'s a city where surfers, painters, poets, and chefs collide daily. As September approaches, the creative community is gearing up for a celebration that could put PV on the cultural map permanently.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Travel',
    created_at: '2026-05-10T00:00:00.000Z',
    updated_at: '2026-05-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 10, 2026',
    language: 'en',
  },
  {
    id: '7',
    title: 'How Mexican Startups Are Solving Local Problems with Global Tech',
    content: 'A new wave of Mexican entrepreneurs is applying AI, blockchain, and clean tech to challenges unique to Latin America — from informal housing to water distribution. Investors from Silicon Valley to Madrid are taking notice.',
    image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Innovation',
    created_at: '2026-05-05T00:00:00.000Z',
    updated_at: '2026-05-05T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'May 5, 2026',
    language: 'en',
  },
  {
    id: '8',
    title: 'Kids Who Code: Mexico City\'s Youth Programming Revolution',
    content: 'At after-school centers from Iztapalapa to Tlalpan, thousands of children are learning to code through community programs. Many of these kids — some as young as 8 — are already building apps that solve problems in their own neighborhoods.',
    image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Youth',
    created_at: '2026-04-28T00:00:00.000Z',
    updated_at: '2026-04-28T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 28, 2026',
    language: 'en',
  },
  {
    id: '9',
    title: 'Interview: Chef Rodrigo Solis on How Jalisco Cuisine Is Going Global',
    content: 'Chef Rodrigo Solis trained in Mexico City, apprenticed in Spain, and came home to Puerto Vallarta to open a restaurant that celebrates Jalisco\'s often-overlooked culinary tradition. His story is a homecoming worth reading.',
    image_url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Interviews',
    created_at: '2026-04-20T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 20, 2026',
    language: 'en',
  },
  {
    id: '10',
    title: 'Monarch Butterflies Return: Conservation Victory in Michoacán',
    content: 'For the first time in a decade, butterfly experts are reporting a significant rebound in the monarch population at the Reserva de la Biosfera Mariposa Monarca. Local communities credit sustainable tourism and reforestation programs for the turnaround.',
    image_url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Community',
    created_at: '2026-04-10T00:00:00.000Z',
    updated_at: '2026-04-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 10, 2026',
    language: 'en',
  },
  {
    id: '11',
    title: 'Women Building Businesses in Oaxaca\'s Textile Capital',
    content: 'In Teotitlán del Valle, a cooperative of women weavers has turned ancestral textile knowledge into a thriving export business. Their story is one of tradition, innovation, and fierce pride in Zapotec identity.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Business',
    created_at: '2026-04-01T00:00:00.000Z',
    updated_at: '2026-04-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'April 1, 2026',
    language: 'en',
  },
  {
    id: '12',
    title: 'Street Photography: The Hidden Beauty of Mexico\'s Markets',
    content: 'Through the lens of six photographers from different parts of the country, this photo essay explores the color, chaos, and community of Mexico\'s mercados — from the massive Central de Abastos to the smallest village tianguis.',
    image_url: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Art & Culture',
    created_at: '2026-03-22T00:00:00.000Z',
    updated_at: '2026-03-22T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: 'March 22, 2026',
    language: 'en',
  },
];

const mockArticlesEs = [
  {
    id: '1-es',
    title: 'Artistas de Puerto Vallarta Haciendo Olas en Todo México',
    content: 'Un colectivo creciente de artistas visuales, muralistas y escultores de Puerto Vallarta están dejando su huella en la escena artística nacional e internacional. Desde la Zona Romántica hasta el Malecón, su trabajo transforma los espacios públicos en museos al aire libre que celebran la cultura de la costa del Pacífico.',
    image_url: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Arte y Cultura',
    created_at: '2026-06-01T00:00:00.000Z',
    updated_at: '2026-06-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '1 de junio, 2026',
    language: 'es',
    featured: true,
  },
  {
    id: '2-es',
    title: 'Jóvenes Emprendedores Transforman el Barrio Santa María',
    content: 'Jóvenes empresarios del histórico Barrio Santa María en La Labyrinha, Ciudad de México, están lanzando negocios sociales que crean empleos y preservan la identidad cultural de su barrio. Conoce a los adolescentes y veinteañeros que construyen el futuro exactamente donde crecieron.',
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Juventud',
    created_at: '2026-05-28T00:00:00.000Z',
    updated_at: '2026-05-28T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '28 de mayo, 2026',
    language: 'es',
  },
  {
    id: '3-es',
    title: 'Entrevista: La Muralista Valentina Reyes sobre Pintar el Alma de Puerto Vallarta',
    content: 'Valentina Reyes creció en la Colonia Emiliano Zapata y hoy sus murales se pueden ver desde San Sebastián del Oeste hasta el paseo de Olas Altas. Nos sentamos con ella para hablar de inspiración, identidad y lo que significa llevar la cultura en el pincel.',
    image_url: 'https://images.unsplash.com/photo-1460574283810-2aab119d8511?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Entrevistas',
    created_at: '2026-05-25T00:00:00.000Z',
    updated_at: '2026-05-25T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '25 de mayo, 2026',
    language: 'es',
  },
  {
    id: '4-es',
    title: 'El Nuevo Sonido de México: Músicos Independientes Redefinen LATAM',
    content: 'Desde estudios de garaje en Guadalajara hasta sesiones en azoteas de Oaxaca, una nueva generación de músicos independientes mezcla ritmos regionales con influencias globales. Las cifras de streaming confirman lo que el público ya siente: la música mexicana está viviendo un momento global.',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Música',
    created_at: '2026-05-20T00:00:00.000Z',
    updated_at: '2026-05-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '20 de mayo, 2026',
    language: 'es',
  },
  {
    id: '5-es',
    title: 'Huertos Comunitarios Florecen en los Barrios Olvidados de la CDMX',
    content: 'En colonias que antes carecían de espacios verdes, los huertos urbanos comunitarios están brotando, uniendo a vecinos y mejorando la seguridad alimentaria. El propio proyecto de huerto de La Labyrinha, el Huerto Monarca, sirve como modelo que se replica en toda la capital.',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Comunidad',
    created_at: '2026-05-15T00:00:00.000Z',
    updated_at: '2026-05-15T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '15 de mayo, 2026',
    language: 'es',
  },
  {
    id: '6-es',
    title: 'Surf, Arte y Alma: La Cultura Creativa de Playa de Puerto Vallarta',
    content: 'Puerto Vallarta es mucho más que sus famosas playas: es una ciudad donde surfistas, pintores, poetas y chefs se cruzan a diario. A medida que se acerca septiembre, la comunidad creativa se prepara para una celebración que podría poner a PV permanentemente en el mapa cultural.',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Viajes',
    created_at: '2026-05-10T00:00:00.000Z',
    updated_at: '2026-05-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '10 de mayo, 2026',
    language: 'es',
  },
  {
    id: '7-es',
    title: 'Cómo las Startups Mexicanas Resuelven Problemas Locales con Tecnología Global',
    content: 'Una nueva ola de emprendedores mexicanos aplica IA, blockchain y tecnología limpia a desafíos únicos de América Latina, desde vivienda informal hasta distribución de agua. Inversionistas de Silicon Valley a Madrid están tomando nota.',
    image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Innovación',
    created_at: '2026-05-05T00:00:00.000Z',
    updated_at: '2026-05-05T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '5 de mayo, 2026',
    language: 'es',
  },
  {
    id: '8-es',
    title: 'Niños que Programan: La Revolución Juvenil de la Programación en la CDMX',
    content: 'En centros extraescolares de Iztapalapa a Tlalpan, miles de niños aprenden a programar gracias a programas comunitarios. Muchos de estos niños, algunos tan jóvenes como de 8 años, ya están creando aplicaciones que resuelven problemas en sus propios barrios.',
    image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Juventud',
    created_at: '2026-04-28T00:00:00.000Z',
    updated_at: '2026-04-28T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '28 de abril, 2026',
    language: 'es',
  },
  {
    id: '9-es',
    title: 'Entrevista: Chef Rodrigo Solís sobre Cómo la Cocina Jalisciense Conquista el Mundo',
    content: 'El chef Rodrigo Solís se formó en la Ciudad de México, hizo su aprendizaje en España y regresó a Puerto Vallarta para abrir un restaurante que celebra la tradición culinaria jalisciense, a menudo subestimada. Su historia es un regreso a casa que vale la pena leer.',
    image_url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Entrevistas',
    created_at: '2026-04-20T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '20 de abril, 2026',
    language: 'es',
  },
  {
    id: '10-es',
    title: 'Las Mariposas Monarca Regresan: Victoria de Conservación en Michoacán',
    content: 'Por primera vez en una década, los expertos en mariposas reportan un repunte significativo en la población monarca en la Reserva de la Biosfera Mariposa Monarca. Las comunidades locales atribuyen el giro al turismo sostenible y los programas de reforestación.',
    image_url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Comunidad',
    created_at: '2026-04-10T00:00:00.000Z',
    updated_at: '2026-04-10T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '10 de abril, 2026',
    language: 'es',
  },
  {
    id: '11-es',
    title: 'Mujeres Construyendo Negocios en la Capital Textil de Oaxaca',
    content: 'En Teotitlán del Valle, una cooperativa de tejedoras ha convertido el conocimiento textil ancestral en un negocio de exportación floreciente. Su historia es de tradición, innovación y feroz orgullo en la identidad zapoteca.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Negocios',
    created_at: '2026-04-01T00:00:00.000Z',
    updated_at: '2026-04-01T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '1 de abril, 2026',
    language: 'es',
  },
  {
    id: '12-es',
    title: 'Fotografía Callejera: La Belleza Oculta de los Mercados de México',
    content: 'A través del lente de seis fotógrafos de diferentes partes del país, este ensayo fotográfico explora el color, el caos y la comunidad de los mercados de México, desde la gigantesca Central de Abastos hasta el tianguis más pequeño de aldea.',
    image_url: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80',
    category: 'Arte y Cultura',
    created_at: '2026-03-22T00:00:00.000Z',
    updated_at: '2026-03-22T00:00:00.000Z',
    author: 'La Monarca Internacional',
    date: '22 de marzo, 2026',
    language: 'es',
  },
];
