// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zikkoadxkakoruygdhgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppa2tvYWR4a2Frb3J1eWdkaGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODQ5NDQsImV4cCI6MjA1NjI2MDk0NH0.qZ8oBiaFIdRWNMSjpxo2j9PP2Ig8OUDeP1Rw8883UZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);